"""Deterministic rendering: ResumeJSON (+ optional TailoringPlan) -> docx/pdf.

This is the only place layout is produced. It never calls Gemini. Given the
same template and the same content, it always produces the same document.

v3: bullets and the summary render as docxtpl RichText built from segments —
unmodified bullets carry their original segments (extracted from the source
docx runs) forward exactly; modified bullets get segments regenerated by the
deterministic bolding rule in segments.py. The LLM never decides bolding.

The template has a fixed number of physical slots (job blocks, bullet lines,
skill cells) baked in by scripts/build_template.py. Experience-block order is
intentionally NOT reorderable (fixed slot capacities); bullet order within a
job is, when the plan supplies a true permutation.
"""
from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path

from docxtpl import DocxTemplate, RichText
from jinja2 import Environment

from .schemas import Bullet, ResumeJSON, Segment, TailoringPlan
from .segments import build_segments, enforce_plan_integrity

_JINJA_ENV = Environment(autoescape=True)

TEMPLATE_PATH = Path(__file__).resolve().parent / "templates" / "resume_template.docx"

MAX_SKILLS = 10
JOB_BULLET_CAPACITY = [9, 8, 7, 3]  # fixed per physical slot, see build_template.py

# Body runs in the source resume are Source Sans Pro 10pt (127000 EMU);
# RichText runs replace the template run's formatting entirely, so both font
# and size must be restated or LibreOffice falls back to a metric-different
# default serif and line wraps drift.
_BODY_SIZE_HALF_POINTS = 20
_BODY_FONT = "Source Sans Pro"


def _to_richtext(segments: list[Segment], fallback_text: str = "") -> RichText:
    rt = RichText()
    if segments:
        for seg in segments:
            rt.add(
                seg.text,
                bold=seg.bold or None,
                size=_BODY_SIZE_HALF_POINTS,
                font=_BODY_FONT,
            )
    elif fallback_text:
        rt.add(fallback_text, size=_BODY_SIZE_HALF_POINTS, font=_BODY_FONT)
    return rt


def _bullet_richtext(
    bullet: Bullet, plan_item_segments: dict[str, list[Segment]]
) -> RichText:
    tailored = plan_item_segments.get(bullet.id)
    if tailored:
        return _to_richtext(tailored)
    return _to_richtext(bullet.segments, bullet.text)


def _plan_segments_by_id(
    resume: ResumeJSON, plan: TailoringPlan | None
) -> dict[str, list[Segment]]:
    """Integrity-checked tailored segments per bullet id. Runs the v3 hard
    rule (coverage + metric preservation with fallback) and derives
    final_segments deterministically from final_text where needed."""
    if plan is None:
        return {}
    enforce_plan_integrity(resume, plan)
    out: dict[str, list[Segment]] = {}
    for item in plan.bullet_plan:
        if item.final_segments:
            out[item.bullet_id] = item.final_segments
        elif item.final_text:
            out[item.bullet_id] = build_segments(item.final_text, item.keywords_injected)
    return out


def _ordered_bullets(exp, plan: TailoringPlan | None) -> list[Bullet]:
    bullets_by_id = {b.id: b for b in exp.bullets}
    order = list(bullets_by_id)
    if plan and exp.id in plan.bullet_order:
        proposed = plan.bullet_order[exp.id]
        # Only honor a true permutation — a plan that drops or invents
        # bullet ids would silently change resume content.
        if sorted(proposed) == sorted(order):
            order = proposed
    return [bullets_by_id[bid] for bid in order]


def build_render_context(resume: ResumeJSON, plan: TailoringPlan | None = None) -> dict:
    cats = list(resume.skills.categories)
    if plan and plan.skills_displayed:
        rank = {name: i for i, name in enumerate(plan.skills_displayed)}
        deprioritized = set(plan.skills_deprioritized)
        cats = sorted(
            cats,
            key=lambda c: (c.name in deprioritized, rank.get(c.name, len(rank))),
        )
    skills_flat = [f"{cat.name}: {', '.join(cat.items)}" for cat in cats]
    skills_flat = (skills_flat + [""] * MAX_SKILLS)[:MAX_SKILLS]

    if plan and plan.tailored_summary:
        # Tailored summary is LLM text: segments via the deterministic rule.
        summary_rt = _to_richtext(build_segments(plan.tailored_summary, []))
    else:
        summary_rt = _to_richtext(resume.summary_segments, resume.summary)

    tailored_segments = _plan_segments_by_id(resume, plan)

    accomplishments = [
        _bullet_richtext(b, tailored_segments) for b in resume.accomplishments
    ]
    accomplishments = (accomplishments + [_to_richtext([], "")] * 6)[:6]

    jobs = []
    for i, exp in enumerate(resume.experience[:4]):
        capacity = JOB_BULLET_CAPACITY[i] if i < len(JOB_BULLET_CAPACITY) else 0
        bullets = [
            _bullet_richtext(b, tailored_segments) for b in _ordered_bullets(exp, plan)
        ]
        bullets = (bullets + [_to_richtext([], "")] * capacity)[:capacity]
        jobs.append(
            {
                "dates": f"{exp.start} - {exp.end} ",
                "header": f"{exp.company} - {exp.title}, {exp.location} ",
                "bullets": bullets,
            }
        )

    certifications = (resume.certifications + [""] * 6)[:6]
    education = resume.education or [{"degree": "", "institution": "", "year": ""}]
    languages = resume.languages or [{"name": "", "level": ""}, {"name": "", "level": ""}]

    return {
        "contact": resume.contact.model_dump(),
        "summary": summary_rt,
        "accomplishments": accomplishments,
        "skills": skills_flat,
        "education": [e if isinstance(e, dict) else e.model_dump() for e in education],
        "languages": [l if isinstance(l, dict) else l.model_dump() for l in languages],
        "jobs": jobs,
        "certifications": certifications,
    }


def render_docx(resume: ResumeJSON, plan: TailoringPlan | None = None) -> bytes:
    context = build_render_context(resume, plan)
    doc = DocxTemplate(str(TEMPLATE_PATH))
    doc.render(context, jinja_env=_JINJA_ENV)
    with tempfile.NamedTemporaryFile(suffix=".docx") as tmp:
        doc.save(tmp.name)
        return Path(tmp.name).read_bytes()


def render_pdf(resume: ResumeJSON, plan: TailoringPlan | None = None) -> bytes:
    docx_bytes = render_docx(resume, plan)
    with tempfile.TemporaryDirectory() as tmp_dir:
        docx_path = Path(tmp_dir) / "resume.docx"
        docx_path.write_bytes(docx_bytes)
        subprocess.run(
            [
                "soffice",
                "--headless",
                "--convert-to",
                "pdf",
                "--outdir",
                tmp_dir,
                str(docx_path),
            ],
            check=True,
            capture_output=True,
        )
        return docx_path.with_suffix(".pdf").read_bytes()
